version: "3"
services:
    central:
        build:
            args:
                ENV: prod
        networks:
            xainet:
                ipv4_address: 172.16.10.6
    model_service_rn50_1:
        build:
            args:
                ENV: prod
        networks:
            xainet:
                ipv4_address: 172.16.10.2
    db_service_imgnet_1000:
        build:
            args:
                ENV: prod
        networks:
            xainet:
                ipv4_address: 172.16.10.3

    xai_service_pytorch_cam:
        build:
            args:
                ENV: prod
        networks:
            xainet:
                ipv4_address: 172.16.10.4

    evaluation_service:
        build:
            args:
                ENV: prod
        networks:
            xainet:
                ipv4_address: 172.16.10.5

networks:
    xainet:
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.10.0/24
