version: "3"
services:
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        ports:
            - 27017:27017
        volumes:
            - xai_fw_volumes:/central/central_storage
    central:
        build:
            args:
                ENV: dev

    model_service_rn50_1:
        build:
            args:
                ENV: dev
        networks:
            xainet:
                ipv4_address: 172.16.10.2
    db_service_imgnet_1000:
        build:
            args:
                ENV: dev
        networks:
            xainet:
                ipv4_address: 172.16.10.3

    xai_service_pytorch_cam:
        build:
            args:
                ENV: dev
        networks:
            xainet:
                ipv4_address: 172.16.10.4

    evaluation_service:
        build:
            args:
                ENV: dev
        networks:
            xainet:
                ipv4_address: 172.16.10.5

networks:
    xainet:
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.10.0/24
