version: "3"
services:
    model_service:
        build:
            dockerfile: ./model_service/Dockerfile
        ports:
            - 5001:5001
    db_service:
        build:
            dockerfile: ./db_service/Dockerfile
        ports:
            - 5002:5002
    xai_service:
        platform: linux/amd64
        build:
            dockerfile: ./xai_service/Dockerfile
        ports:
            - 5003:5003

    evaluation_service:
        build:
            dockerfile: ./evaluation_service/Dockerfile
        ports:
            - 5004:5004
