version: '3'
services:
    model_service:
      build: 
        context: model_service
        dockerfile: Dockerfile
      image: xai_model_service
      ports:
        - 5001:5001
      networks:
        xainet:
          ipv4_address: 172.16.10.2
    
    db_service:
      build:
        context: db_service
        dockerfile: Dockerfile
      image: xai_db_service
      ports:
        - 5002:5002
      networks:
        xainet:
          ipv4_address: 172.16.10.3

    xai_service:
      build:
        context: xai_service
        dockerfile: Dockerfile
      image: xai_xai_service
      ports:
        - 5003:5003
      networks:
        xainet:
          ipv4_address: 172.16.10.4

    evaluation_service:
      build:
        context: evaluation_service
        dockerfile: Dockerfile
      image: xai_evaluation_service
      ports:
        - 5004:5004
      networks:
        xainet:
          ipv4_address: 172.16.10.5

networks:
  xainet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.10.0/24 