version: "3"
services:
    central:
        build:
            dockerfile: ./backend/central/Dockerfile
        ports:
            - 5006:5006
        volumes:
            - xai_fw_volumes:/central/central_storage

    azure_blob:
        build:
            dockerfile: ./backend/db_service/azure_blob/Dockerfile
        ports:
            - 5009:5009
        volumes:
            - xai_fw_volumes:/db_service/azure_blob/azure_blob_storage

    resnet50:
        build:
            dockerfile: ./backend/model_service/resnet50/Dockerfile
        ports:
            - 5001:5001
        volumes:
            - xai_fw_volumes:/model_service/resnet50/resnet50_storage

    grad_cam:
        # platform: linux/amd64
        build:
            dockerfile: ./backend/xai_service/pytorch_cam/Dockerfile
        ports:
            - 5003:5003
        volumes:
            - xai_fw_volumes:/xai_service/pytorch_cam/pt_cam_storage

    eval:
        build:
            dockerfile: ./backend/evaluation_service/Dockerfile
        ports:
            - 5004:5004
        volumes:
            - xai_fw_volumes:/evaluation_service/evaluation_storage

    # azure-cog:
    #     build:
    #         dockerfile: ./backend/model_service/azure_cog/Dockerfile
    #     ports:
    #         - 5007:5007
    #     volumes:
    #         - xai_fw_volumes:/central/central_storage

volumes:
    xai_fw_volumes:
    mongo:
