version: "3"
services:
    mongo:
        image: mongo
        # restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        ports:
            - 27017:27017
        volumes:
            - mongo:/data

    azure_blob:
        env_file:
            - ./.env.dev
        depends_on:
            - mongo

    central:
        env_file:
            - ./.env.dev
        depends_on:
            - mongo
            - azure_blob

    resnet50:
        env_file:
            - ./.env.dev
        depends_on:
            - central

    grad_cam:
        env_file:
            - ./.env.dev
        depends_on:
            - central
        environment:
            - CAM_METHOD=grad-cam

    eval:
        env_file:
            - ./.env.dev
        depends_on:
            - central
