version: "3"
services:
    central:
        build:
            dockerfile: ./central/Dockerfile
        ports:
            - 5006:5006
        volumes:
            - xai_fw_volumes:/central/central_storage
    model_service_rn50_1:
        build:
            dockerfile: ./model_service/resnet50/Dockerfile
        ports:
            - 5001:5001
        volumes:
            - xai_fw_volumes:/model_service/resnet50/resnet50_storage
    db_service_imgnet_1000:
        build:
            dockerfile: ./db_service/image_net_1000/Dockerfile
        ports:
            - 5002:5002
        volumes:
            - xai_fw_volumes:/db_service/image_net_1000/image_net_1000_storage
    xai_service_pytorch_cam:
        # platform: linux/amd64
        build:
            dockerfile: ./xai_service/pytorch_cam/Dockerfile
        ports:
            - 5003:5003
        volumes:
            - xai_fw_volumes:/xai_service/pytorch_cam/pt_cam_storage
    evaluation_service:
        build:
            dockerfile: ./evaluation_service/Dockerfile
        ports:
            - 5004:5004
        volumes:
            - xai_fw_volumes:/evaluation_service/evaluation_storage

volumes:
    xai_fw_volumes:
