version: 0.2

phases:
  install:
    commands:
      # Install Google Cloud SDK
      - curl -sSL https://sdk.cloud.google.com | bash
      - source $HOME/google-cloud-sdk/path.bash.inc
      - gcloud version

      # Adding mongo connection string
      - cd backend
      - MONGO_CONN_STR=$(aws ssm get-parameter --name mongo-dev --with-decryption --query "Parameter.Value" --output text)
      - echo "$MONGO_CONN_STR" > mongo.dev.conf

      # Adding azure connection string
      - cd central
      - mkdir -p central_storage/tmp
      - cd central_storage/tmp
      - CONN_STR=$(aws ssm get-parameter --name azure-con-str --with-decryption --query "Parameter.Value" --output text)
      - echo "$CONN_STR" > az_blob_connection_str.json
      - cd ../../../db_service/azure_blob
      - mkdir -p azure_blob_storage/tmp
      - cd azure_blob_storage/tmp
      - echo "$CONN_STR" > az_blob_connection_str.json
      - cd ../../../../
      - cd model_service/azure_cog
      - mkdir -p azure_cog_storage/tmp
      - cd azure_cog_storage/tmp
      - echo "$CONN_STR" > api.conf.json
      - cat api.conf.json
      - ls
      - cd ../../../../

  pre_build:
    commands:
      # Install Google Cloud SDK
      - echo "Executing pre-build commands..."
      # Authenticate with Google Cloud
      - echo $GCLOUD_SERVICE_KEY > gcloud-service-key.json
      - gcloud auth activate-service-account --key-file=gcloud-service-key.json
      - gcloud config set project xai-service
      - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
      - gcloud auth configure-docker -q
      # Delete existing images
      - (gcloud container images describe gcr.io/xai-service/backendcentral:latest >/dev/null 2>&1 && gcloud container images delete gcr.io/xai-service/backendcentral:latest --force-delete-tags -q) || echo "Image does not exist."
      - (gcloud container images describe gcr.io/xai-service/backendazureblob:latest >/dev/null 2>&1 && gcloud container images delete gcr.io/xai-service/backendazureblob:latest --force-delete-tags -q) || echo "Image does not exist."
      - (gcloud container images describe gcr.io/xai-service/backendazurecog:latest >/dev/null 2>&1 && gcloud container images delete gcr.io/xai-service/backendazurecog:latest --force-delete-tags -q) || echo "Image does not exist."
      - (gcloud container images describe gcr.io/xai-service/backendevaluationservice:latest >/dev/null 2>&1 && gcloud container images delete gcr.io/xai-service/backendevaluationservice:latest --force-delete-tags -q) || echo "Image does not exist."
      - (gcloud container images describe gcr.io/xai-service/backendrestnet50:latest >/dev/null 2>&1 && gcloud container images delete gcr.io/xai-service/backendrestnet50:latest --force-delete-tags -q) || echo "Image does not exist."
      - (gcloud container images describe gcr.io/xai-service/backendgradcam:latest >/dev/null 2>&1 && gcloud container images delete gcr.io/xai-service/backendgradcam:latest --force-delete-tags -q) || echo "Image does not exist."


  build:
    commands:
      - docker compose build

      - docker tag backend-central gcr.io/xai-service/backendcentral
      - docker push gcr.io/xai-service/backendcentral

      - docker tag backend-azureblob gcr.io/xai-service/backendazureblob
      - docker push gcr.io/xai-service/backendazureblob

      - docker tag backend-azurecog gcr.io/xai-service/backendazurecog
      - docker push gcr.io/xai-service/backendazurecog

      - docker tag backend-evaluationservice gcr.io/xai-service/backendevaluationservice
      - docker push gcr.io/xai-service/backendevaluationservice

      - docker tag backend-restnet50 gcr.io/xai-service/backendrestnet50
      - docker push gcr.io/xai-service/backendrestnet50

      - docker tag backend-gradcam gcr.io/xai-service/backendgradcam
      - docker push gcr.io/xai-service/backendgradcam
      # Run kubectl commands
      - gcloud components install gke-gcloud-auth-plugin -q
      - gcloud container clusters describe backendcentral --location=us-central1 &> /dev/null || gcloud container clusters create-auto backendcentral --location=us-central1
      - gcloud container clusters get-credentials backendcentral --location=us-central1
      - kubectl get deployment backendcentral --no-headers=true --output=name 2>/dev/null | xargs -I {} kubectl delete deployment {}
      - kubectl create deployment backendcentral --image=gcr.io/xai-service/backendcentral:latest
      - kubectl expose deployment backendcentral --type LoadBalancer --port 5006 --target-port 5006


      - gcloud container clusters describe backendazureblob --location=us-central1 &> /dev/null || gcloud container clusters create-auto backendazureblob --location=us-central1
      - gcloud container clusters get-credentials backendazureblob --location=us-central1
      - kubectl get deployment backendazureblob --no-headers=true --output=name 2>/dev/null | xargs -I {} kubectl delete deployment {}
      - kubectl create deployment backendazureblob --image=gcr.io/xai-service/backendazureblob:latest
      - kubectl expose deployment backendazureblob --type LoadBalancer --port 5009 --target-port 5009

      - gcloud container clusters describe backendazurecog --location=us-central1 &> /dev/null || gcloud container clusters create-auto backendazurecog --location=us-central1
      - gcloud container clusters get-credentials backendazurecog --location=us-central1
      - kubectl get deployment backendazurecog --no-headers=true --output=name 2>/dev/null | xargs -I {} kubectl delete deployment {}
      - kubectl create deployment backendazurecog --image=gcr.io/xai-service/backendazurecog:latest
      - kubectl expose deployment backendazurecog --type LoadBalancer --port 5007 --target-port 5007

      - gcloud container clusters describe backendevaluationservice --location=us-central1 &> /dev/null || gcloud container clusters create-auto backendevaluationservice --location=us-central1
      - gcloud container clusters get-credentials backendevaluationservice --location=us-central1
      - kubectl get deployment backendevaluationservice --no-headers=true --output=name 2>/dev/null | xargs -I {} kubectl delete deployment {}
      - kubectl create deployment backendevaluationservice --image=gcr.io/xai-service/backendevaluationservice:latest
      - kubectl expose deployment backendevaluationservice --type LoadBalancer --port 5004 --target-port 5004

      - gcloud container clusters describe backendrestnet50 --location=us-central1 &> /dev/null || gcloud container clusters create-auto backendrestnet50 --location=us-central1
      - gcloud container clusters get-credentials backendrestnet50 --location=us-central1
      - kubectl get deployment backendrestnet50 --no-headers=true --output=name 2>/dev/null | xargs -I {} kubectl delete deployment {}
      - kubectl create deployment backendrestnet50 --image=gcr.io/xai-service/backendrestnet50:latest
      - kubectl expose deployment backendrestnet50 --type LoadBalancer --port 5001 --target-port 5001

      - gcloud container clusters describe backendgradcam --location=us-central1 &> /dev/null || gcloud container clusters create-auto backendgradcam --location=us-central1
      - gcloud container clusters get-credentials backendgradcam --location=us-central1
      - kubectl get deployment backendgradcam --no-headers=true --output=name 2>/dev/null | xargs -I {} kubectl delete deployment {}
      - kubectl create deployment backendgradcam --image=gcr.io/xai-service/backendgradcam:latest
      - kubectl expose deployment backendgradcam --type LoadBalancer --port 5003 --target-port 5003

artifacts:
  files:
    - "**/*"
