base_url: "http://127.0.0.1:5006"

services:
  db:
    - url: "http://127.0.0.1:5009/azure_blob"
      info:
        exp_name: "db"

  model:
    - url: "http://127.0.0.1:5001/resnet50"
      info:
        exp_name: "resnet50"
    - url: "http://127.0.0.1:5007/azure_cog"
      info:
        exp_name: "azurecog"

  xai:
    - url: "http://127.0.0.1:5021/xai/pt_cam/layercam"
      info:
        exp_name: "layercam"
    - url: "http://127.0.0.1:5019/xai/pt_cam/eigencam"
      info:
        exp_name: "eigencam"
    - url: "http://127.0.0.1:5003/xai/pt_cam"
      info:
        exp_name: "grad-cam"

  evaluation:
    - url: "http://127.0.0.1:5004/evaluation"
      info:
        exp_name: "eval"


xai_task_sheets:
  - task_type: "xai"
    db_service_executor_id: "VVIQ20M66K"
    model_service_executor_id: "MV7I4W1KBQ"
    xai_service_executor_id: "W3P2CFF3LM"
    evaluation_service_executor_id: "GGJR7B1OTA"  #To be deleted later
    task_parameters:
      method_name: "grad-cam"
      data_set_name: "imagenet1000"
      data_set_group_name: "g0"
      model_name: "resnet50"
      executor_config:
        use_pytorch_multiprocess: true
    task_sheet_name: "xai1"
  - task_type: "xai"
    db_service_executor_id: "VVIQ20M66K"
    model_service_executor_id: "MV7I4W1KBQ"
    xai_service_executor_id: "U63QXT0PGD"
    evaluation_service_executor_id: "GGJR7B1OTA"
    task_parameters:
      method_name: "layer-cam"
      data_set_name: "imagenet1000"
      data_set_group_name: "g0"
      model_name: "resnet50"
      executor_config:
        use_pytorch_multiprocess: true
    task_sheet_name: "xai2"

xai_task_sheet_ids:
  - task_sheet_id: "OKN4612CS6X63NX"
  - task_sheet_id: "EFFXZXNZ5FJCFZV"

evaluation_task_sheets:
  - task_type: "evaluation"
    db_service_executor_id: "VVIQ20M66K"
    model_service_executor_id: "MV7I4W1KBQ" 
    xai_service_executor_id: "W3P2CFF3LM"
    evaluation_service_executor_id: "GGJR7B1OTA"   
    task_parameters:
      explanation_task_ticket: "Dynamically_fetched_Ticket_ID"
    task_sheet_name: "eval1"
  - task_type: "evaluation"
    db_service_executor_id: "VVIQ20M66K"
    model_service_executor_id: "MV7I4W1KBQ" 
    xai_service_executor_id: "U63QXT0PGD"
    evaluation_service_executor_id: "GGJR7B1OTA"
    task_parameters:
      explanation_task_ticket: "Dynamically_fetched_Ticket_ID"
    task_sheet_name: "eval2"


pipelines:
  - name: "pipeline1"
    xai_task_sheet_id: "RDRH2YFZZRKTBVA"
    evaluation_task_sheet_id: "WUAIZX8HY7XNIQP"
  - name: "pipeline2"
    xai_task_sheet_id: "GS4FWWIRWPK4ZLJ"
    evaluation_task_sheet_id: "0KVDMHIZMO4S181"
  - name: "pipeline3"
    xai_task_sheet_id: "RDRH2YFZZRKTBVA"
    evaluation_task_sheet_id: "0KVDMHIZMO4S181"