base_url: "http://35.185.126.177:5006"

services:
  db:
    - url: "http://34.42.74.31:5009/azure_blob"
      info:
        exp_name: "db"

  model:
    - url: "http://35.223.31.209:5001/resnet50"
      info:
        exp_name: "resnet50"

  xai:
    - url: "http://34.139.58.133:5003/xai/pt_cam"
      info:
        exp_name: "grad-cam"

  evaluation:
    - url: "http://34.138.139.235:5004/evaluation"
      info:
        exp_name: "eval"


xai_task_sheets:
  - task_type: "xai"
    db_service_executor_id: "430EHL6ISY"
    model_service_executor_id: "CJP1X4NJIZ"
    xai_service_executor_id: "SHI9K80B62"
    evaluation_service_executor_id: "7G0NSB6Y5I"  #To be deleted later
    task_parameters:
      method_name: "grad-cam"
      data_set_name: "imagenet1000"
      data_set_group_name: "g0"
      model_name: "resnet50"
      executor_config:
        use_pytorch_multiprocess: true
    task_sheet_name: "xai1"

evaluation_task_sheets:
  - task_type: "evaluation"
    db_service_executor_id: "430EHL6ISY"
    model_service_executor_id: "CJP1X4NJIZ" 
    xai_service_executor_id: "SHI9K80B62"
    evaluation_service_executor_id: "7G0NSB6Y5I"   
    task_parameters:
      explanation_task_ticket: "Dynamically_fetched_Ticket_ID"
    task_sheet_name: "eval1"


pipelines:
  - name: "pipeline1"
    xai_task_sheet_id: "8IU7NIAVYWJ0D0L"
    evaluation_task_sheet_id: "VKNWMX6I9O2OVHF"