services:
    local-mysql:
        platform: linux/x86_64
        image: mysql:5.7.40
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_USER: xai
            MYSQL_PASSWORD: mysql_pw
            MYSQL_ROOT_PASSWORD: mysql_rt_pw
            MYSQL_DATABASE: data
        volumes:
            - xaifw-mysql:/var/lib/mysql
        ports:
            - 3306:3306

# docker managed volume
volumes:
    xaifw-mysql:
