
time_tail = '__time_tail__'
task_ticket = 'task_ticket'
publisher = 'publisher'
task_name = 'task_name'
task_status = 'task_status'
db_service_url = 'db_service_url'
model_service_url = 'model_service_url'
xai_service_url = 'xai_service_url'
evaluation_service_url = 'evaluation_service_url'
start_time = 'start_time'
formated_start_time = 'formated_start_time'
end_time = 'end_time'
formated_end_time = 'formated_end_time'
